on:
  push:
    branches:
     - master
name: Build and deploy to GitHub Pages on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy Zola site
      uses: shalzz/zola-deploy-action@v0.16.1
      env:
        PAGES_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
